### PR TITLE
Add bors

### LINKED ISSUE #4: Add bors

### PR DESCRIPTION
**Pull request by curquiza**
Closes #4

### CODE REVIEW

**Comment by curquiza** [comment]
bors try

**Comment by curquiza** [comment]
bors try

**Comment by curquiza** [comment]
From now, @CaroFG, you can only merge by using bors, not in the classic way with the `Merge pull request` GitHub button.

More about bors (a guide I wrote) -> https://github.com/meilisearch/integration-guides/blob/main/guides/bors.md

TLDR:
You can test the PR with `bors try`
You can merge by doing `bors merge` (you have to approve my PR first 😉)

**Review by CaroFG — APPROVED** [review]

**Comment by curquiza** [comment]
Caro, could you please try to merge with bors?

**Comment by CaroFG** [comment]
bors try

**Comment by CaroFG** [comment]
I don't have the rights to merge @curquiza

**Comment by CaroFG** [comment]
bors merge

**Pull request merged**
