### PR TITLE
Properly clean up indexes after test suite runs

### LINKED ISSUE #298: Indexes not cleaned up after test suite
**Description**
The test suite does not clean up all indexes after itself.

**Expected behavior**
After the test suite is run, the meilisearch instance will have no test indexes.

**Current behavior**
The test suite left behind several indexes after it was run.

**Screenshots or Logs**
```ruby
# get a list of safe indexes in local or CI
def safe_index_list
  list = MeiliSearch::Rails.client.indexes['results']
  list = list.select { |index| index.uid.include?(SAFE_INDEX_PREFIX) }
  list.sort_by { |index| index.primary_key || '' }
end
```
This method does not clean up properly since `MeiliSearch::Client.indexes` has a limit of 20 by default. Increasing the limit is not a suitable solution since we can make no safe assumptions about the number of existing indexes, and it is possible that iterating through all the indexes could be costly. 

In addition, one of the indexes does not use the `SAFE_INDEX_PREFIX`:

```ruby
class Post < ActiveRecord::Base
  # snip
  meilisearch synchronous: true do
    attribute :comments do
      comments.map(&:body)
    end
  end
  # snip
end
```

### PR DESCRIPTION
**Pull request by ellnix**
# Pull Request

## Related issue
Fixes #298 

## PR checklist
Please check if your PR fulfills the following requirements:
- [X] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [X] Have you read the contributing guidelines?
- [X] Have you made sure that the title is accurate and descriptive of the changes?

### CODE REVIEW

**Review by brunoocasali — APPROVED** [review]
I don't think that's a huge deal, but if we can make it tidy it is ok to me!

LGTM!!

Thanks again @ellnix you rocks!

**Comment by ellnix** [comment]
@brunoocasali I'm sorry, rebasing made the approval stale...

**Review by brunoocasali — APPROVED** [review]
LGTM!

**Comment by ellnix** [comment]
bors merge

**Pull request merged**
