### PR TITLE
Ensure bug reports will inform Meilisearch server version

### PR DESCRIPTION
**Pull request by brunoocasali**

### CODE REVIEW

**Comment by curquiza** [comment]
Should be changed in every repository, not only this one, using our automation tool :)

**Review by curquiza — APPROVED** [review]

**Comment by brunoocasali** [comment]
@curquiza I'm not sure, because in this case, the names make the confusion because `meilisearch` is the name of our ruby gem. Maybe this could be replicated only in the integrations, not in the SDKs.

for the record:

- https://github.com/meilisearch/meilisearch-symfony/blob/main/.github/ISSUE_TEMPLATE/bug_report.md
- https://github.com/meilisearch/meilisearch-php/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

Anyway, If you think this could be a great change let's do that!

**Comment by brunoocasali** [comment]
bors merge

**Comment by curquiza** [comment]
> @curquiza I'm not sure, because in this case, the names make the confusion because meilisearch is the name of our ruby gem. Maybe this could be replicated only in the integrations, not in the SDKs.

I agree! My bad!

**Pull request merged**
