### PR TITLE
first working version

### PR DESCRIPTION
**Pull request by CaroFG**

### CODE REVIEW

**Review by curquiza — CHANGES_REQUESTED** [review]
Could you remove:
- the `Gemfile.lock` and put it in the .gitignore
- the CONTRIBUTING
- the MAINTAINERS.md

Otherwise, thanks a lot for this first version! This is awesome!!!

**Review by curquiza — APPROVED** [review]
🚀

**Comment by curquiza** [comment]
(merge when you want @CaroFG)

**Comment by CaroFG** [comment]
I am not authorized to merge @curquiza

**Comment by curquiza** [comment]
you are now @CaroFG :D

**Comment by fharper** [comment]
Yeah!

**Pull request merged**
