### PR TITLE
Remove duplicated gem versions from the gemspec/Gemfile

### PR DESCRIPTION
**Pull request by brunoocasali**
This removes the duplicated gem from the gemspec/Gemfile, I could not found a reason to be like this (I also checked for other well know gems and they only define dependencies in the gemspec, the Gemfile contains only dependencies for tests/development/benchmarks, etc - not shipped to the end-user).

### CODE REVIEW

**Review by curquiza — DISMISSED** [review]
👌

**Comment by curquiza** [comment]
- Looks like the tests are failing, is it related to this?
- why this PR is merged into `bump-meilisearch-v0.27.0`? Does not look like it's related to v0.27.0, right?

**Comment by brunoocasali** [comment]
@curquiza 
> Looks like the tests are failing, is it related to this?

Yeah, I was trying to understand why the removal should not be problematic, but in the end was, because the `gemspec` was not defined in the `Gemfile` - took me a couple of good minutes to see that 😅 .

> why this PR is merged into bump-meilisearch-v0.27.0? Does not look like it's related to v0.27.0, right?

Yup! I was merging there because there is a breaking change in the docker, without the bump I would not be able to run the CI :)

**Review by curquiza — APPROVED** [review]
🚀

**Comment by brunoocasali** [comment]
bors merge

**Pull request merged**
