### PR TITLE
Add pre-release tests in github action

### PR DESCRIPTION
**Pull request by alallema**

### CODE REVIEW

**Review by bidoubiwa — DISMISSED** [review]
LGTM 🔥

**Comment by alallema** [comment]
bors merge

**Comment by bidoubiwa** [comment]
bors merge

**Comment by curquiza** [comment]
@bidoubiwa, as I explained, you have the admin right during my holiday, not the access to merge everywhere. If you want absolutely merge something (like an emergency PR) merge via GH

**Review by curquiza — DISMISSED** [review]
thanks @alallema!

bors merge

**Comment by curquiza** [comment]
bors merge-

**Review by curquiza — APPROVED** [review]
bors merge

**Pull request merged**
