### PR TITLE
Update CI to use Ubuntu 22.04

### LINKED ISSUE #306: All CI tests with Rails 7 fail
**Description**
All GitHub actions jobs with Rails 7 fail. This means that no PRs can be merged currently.

After almost 2 hours of trying to find out why:
- Although the `tests.yml` file specifies `RAILS_VERSION: 7.0` which should prevent bundler from going to `7.1` (due to the pessimistic version constraint `~>`) the workflow is now run with Rails [`7.1.0`](https://github.com/meilisearch/meilisearch-rails/actions/runs/6341168191/job/18040971613?pr=299#step:3:229) while in the past it was run with Rails [`7.0.x`](https://github.com/meilisearch/meilisearch-rails/actions/runs/6341168191/job/18040971613?pr=299#step:3:103)
  - I do not know why this happens, maybe Github actions casts 7.0 to an int somehow?
- The `sqlite3` package on `Ubuntu 20.04` seems to have compatibility with [sqlite changes in Rails 7.1](https://edgeguides.rubyonrails.org/7_1_release_notes.html#active-record-notable-changes), resulting in all database-backed tests failing
  - Ubuntu freezes package versions and only provides security updates to them in LTS releases
  
  
We should either 
- specify `7.0.8` as the Rails 7 version (not preferred, we just kick the problem down the road)
- change the OS used in github actions to something more modern

P. S.: I am still investigating this, `sqlite3` is just my working theory for the moment, but it could be a different compatibility issue.

Edit 1: It definitely is `sqlite`, I confirmed it by switching to postgres on a vm. `sqlite` has the same errors as github actions while `postgres` passes all tests.
[postgres_rspec_run.log](https://github.com/meilisearch/meilisearch-rails/files/13166531/postgres_rspec_run.log)
[sqlite_rspec_run.log](https://github.com/meilisearch/meilisearch-rails/files/13166532/sqlite_rspec_run.log)

### PR DESCRIPTION
**Pull request by ellnix**
## Related issue
Fixes #306

### CODE REVIEW

**Review by curquiza — COMMENTED** [review]
Thank you for the PR @ellnix 

Can you update the ubuntu version everywhere in the CI manifest files to avoid future maintenance (when 20.04 will be deprecated)?

**Comment by ellnix** [comment]
> Thank you for the PR @ellnix
> 
> Can you update the ubuntu version everywhere in the CI manifest files to avoid future maintenance (when 20.04 will be deprecated)?

Sure thing, for some reason I assumed it would just grab that setting everywhere. I'm not familiar with github actions, which is why I let that issue sit for so long.

**Review by curquiza — APPROVED** [review]
Good for me, I let you merge if you are ok @ellnix

**Comment by ellnix** [comment]
> Good for me, I let you merge if you are ok @ellnix

Oh, thanks. I am assuming I use `bors` in this case?

**Comment by ellnix** [comment]
bors merge

**Comment by ellnix** [comment]
bors merge

**Comment by ellnix** [comment]
For some reason bors does not like me and it's failing with 403 @curquiza

**Comment by curquiza** [comment]
@ellnix it's happening sometimes, merge manually in this case. I don't know what to do with this kind of issue 😓

**Pull request merged**
