### PR TITLE
Update version for the next release (v0.7.1)

### PR DESCRIPTION
**Pull request by brunoocasali**

### CODE REVIEW

**Comment by bidoubiwa** [comment]
Is it normal that all the tests are failing?

**Comment by brunoocasali** [comment]
> Is it normal that all the tests are failing?

yes @bidoubiwa I need to release the ruby first :)

**Review by bidoubiwa — APPROVED** [review]
LGTM 🔥

**Comment by brunoocasali** [comment]
bors merge

**Pull request merged**
